version: '3'

services:
  web:
    build:
      context: Golang
    ports:
      - 1323:1323
    links:
      - database
    volumes:
      - $PWD:/home

  database:
    image:
      mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - $PWD/Country-DB/world.sql:/docker-entrypoint-initdb.d/world.sql
